version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - mkdir lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - zip -g deployment_package1.zip index.py
  post_build:
    commands:
      - echo "Updating lambda Function 1..."
      - aws lambda update-function-code --function-name LF --zip-file fileb://deployment_package1.zip
      - echo "DONE!!"